server:
  port: 8083

spring:
  application:
    name: inventory-service
  profiles: 8083
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  redis:
    password: xiaoqiang
  rabbitmq:
    host: learn
    port: 5672
    username: admin
    password: xiaoqiang
    cache:
      channel:
        size: 50
        checkout-timeout: 10s
    connection-timeout: 1s
    publisher-confirms: true
    publisher-returns: true

stock:
  queue: order-stock-queue
rabbit:
  connection:
    thread:
      prefix: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@micoservice1:8761/eureka/, http://xiaoqiang:xiaoqiang@micoservice2:8762/eureka/, http://xiaoqiang:xiaoqiang@micoservice3:8763/eureka/

---
server:
  port: 8084

spring:
  application:
    name: inventory-service
  profiles: 8084
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  redis:
    password: xiaoqiang
  rabbitmq:
    host: learn
    port: 5672
    username: admin
    password: xiaoqiang
    cache:
      channel:
        size: 50
        checkout-timeout: 10s
    connection-timeout: 1s
    publisher-confirms: true
    publisher-returns: true

stock:
  queue: order-stock-queue
rabbit:
  connection:
    thread:
      prefix: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@micoservice1:8761/eureka/, http://xiaoqiang:xiaoqiang@micoservice2:8762/eureka/, http://xiaoqiang:xiaoqiang@micoservice3:8763/eureka/

---
server:
  port: 8085

spring:
  application:
    name: inventory-service
  profiles: 8085
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  redis:
    password: xiaoqiang
  rabbitmq:
    host: learn
    port: 5672
    username: admin
    password: xiaoqiang
    cache:
      channel:
        size: 50
        checkout-timeout: 10s
    connection-timeout: 1s
    publisher-confirms: true
    publisher-returns: true

stock:
  queue: order-stock-queue
rabbit:
  connection:
    thread:
      prefix: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://xiaoqiang:xiaoqiang@micoservice1:8761/eureka/, http://xiaoqiang:xiaoqiang@micoservice2:8762/eureka/, http://xiaoqiang:xiaoqiang@micoservice3:8763/eureka/
